[package]
name = "puck_liveview"
version = "0.1.0"
authors = ["teymour-aldridge <teymour.aldridge@icloud.com>"]
edition = "2018"

[dependencies]
derive_builder = "0.10.2"
puck = { path = "../puck" }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
maplit = "1.0.2"
lunatic = "0.3.10"
proptest = { version = "1.0.0", optional = true }

[target.'cfg(not(target_arch="wasm32"))'.dependencies.malvolio]
git = "https://github.com/lovelace-edu/lovelace"
features = ["pub_fields", "with_proptest"]
rev = "61b1523"

[target.'cfg(target_arch="wasm32")'.dependencies.malvolio]
git = "https://github.com/lovelace-edu/lovelace"
features = ["pub_fields"]
rev = "61b1523"

[dev-dependencies]
insta = "1.7.1"
scraper = "0.12.0"

[features]
apply = []
_test_fuzzing = ["proptest", "apply"]
